### ISSUE TITLE
Improve Styling Structure

### ISSUE THREAD

**Issue by thainan10** [SharebookBR/sharebook-frontend#103]
I think we can improve the styling structure:
- Change from css to some pre processed (I recommend scss);
- Create a default style asset file to store all the colours;
- Create mixins with default styles to avoid repetition;

The idea is to have two main files: one to store the default properties such as fonts, colours, etc., and the other to store mixins of default styling which is reused in other parts of the code.

**Comment by raffacabofrio** [comment]
@thainan10 por favor não desanima com minha ação agora. Estou fechando essa issue.

Acontece que no nosso projeto, o lugar mais adequado pra PROPOR esse tipo de mudança eh no nosso canal FRONTEND la no SLACK.

Suas ideias são super bem vindas. Apenas alinhando o canal mais adequado.
