### ISSUE TITLE
Captcha não funciona no fale-conosco.

### ISSUE THREAD

**Issue by raffacabofrio** [SharebookBR/sharebook-frontend#127]
Ambiente: produção e os demais.

Ao clicar no Recaptcha fica carregando eternamente.

<img width="295" alt="screenshot_106" src="https://user-images.githubusercontent.com/10622114/46444645-3fb27480-c749-11e8-9d85-d50260a5fa31.png">

**Comment by raffacabofrio** [comment]
Eu suspeito que o recaptcha não confie no nosso domínio. Talvez a gente precise provar que somos donos do domínio. Em outros produtos da Google ja fiz isso via registros dns personaizados. Talvez esse seja o caminho pra solucionar.

**Comment by wantero** [comment]
O problema é que o JS do componente do TAGGBOX está gerando erro no console e esses erros estão quebrando o reCAPTCHA. Problema já identificado.

**Comment by wantero** [comment]
Ajustes liberado em Produção.
