### ISSUE TITLE
Problema ao criar conta no mobile

### ISSUE THREAD

**Issue by maxgomes92** [SharebookBR/sharebook-frontend#128]
Na tela de cadastro não está sendo possível digitar, aprece um número, aí quando completa o DDD, ele some e não deixa digitar mais nada.

https://i.imgur.com/4ISrYhF.jpg

O cep não está sendo possível digitar o final, para no "-".
Exemplo: "12311-"

Poderia também ajustar o e-mail.
Quando tem um espaço a mais no final ele fica inválido.
Poderia implementar um trim() no valueChanges do FormControl.

Aparelho: Samsung SMG610-M
Android: 7

https://i.imgur.com/dXRyt0S.jpg
https://i.imgur.com/LnuWIAP.jpg

**Comment by wantero** [comment]
Bug corrigido. Era problema no Build pela nossa ferramente de CI.

**Comment by wantero** [comment]
Bug corrigido. Era problema no Build pela nossa ferramente de CI.
