### ISSUE TITLE
Campo telefone não aceita digitar nenhum valor

### ISSUE THREAD

**Issue by rattones** [SharebookBR/sharebook-frontend#129]
na hora de editar/preencher o campo de telefone a máscara remove o valor digita após a digitação do 2 caractere 
ex.: 37998458823 
ou 037998458823 
ou 11998761234 
ou 011998761234 
ou 21998761234 
ou 021998761234 
valores testados ... 

erro pode estar relacionado a este erro de script durante o carregamento da página

https://drive.google.com/open?id=1USAGdTaQ4B9-yINLicoH0CUr3Ol_2R3g

**Comment by wantero** [comment]
@rattones tem alguma coisa muito estranha, pois isso funcionava e passou a não funcionar.

Estou rodando local a mesma versão que está no dev.sharebook.com.br e no dev.sharebook.com.br o erro acontece, porém rodando local com npm run start a mesma não acontece. 

Esse erro no carregamento da página eu já tinha identificado que começou a aparecer após a atualização do Chrome #121 e isso não é o problema que está gerando a quebra no campo de telefone, pois esse erro também acontece no meu localhost e não quebrou o campo.

Creio que seja algo relacionado no nosso npm run build:prod que está quebrando isso.

Fiz também um teste no nosso ambiente produtivo no Edge e o erro persistiu.

abs,

**Comment by wantero** [comment]
Bug corrigido. Era problema no Build pela nossa ferramente de CI.
