### ISSUE TITLE
Novidades da Fanpage - instável

### ISSUE THREAD

**Issue by raffacabofrio** [SharebookBR/sharebook-frontend#143]
Na home temos uma área chamada 'Novidades da Fanpage'. Porém está intermitente. As vezes carrega. As vezes não carrega.

Precisamos de uma forma mais estável e confiável de carregar os posts.

**Comment by ErisvaldoCorreia** [comment]
Dependendo do navegador utilizado, ela não esta carregando em momento algum! Cito exemplo o Firefox.

**Comment by wantero** [comment]
Componente de novidades foi removido do site.
