### ISSUE TITLE
Trocar folha de estilo de CSS para SASS

### ISSUE THREAD

**Issue by thiagosantoscunha** [SharebookBR/sharebook-frontend#187]
_"Eu sempre quando via o SASS, tinha medo da tech. Mas depois de 3 dias de estudo há 2 anos atrás, consegui absorver muita coisa relacionada a esta tecnologia"._

Existem alguns benefícios ao usar o Sass. Vou listar algumas delas:

- Definição de variáveis
- Ótimo para programação funcional (Mixins)
- Classes aninhadas (Escopo)
- Interpolação
- Operações matmáticas ideais para manter uma dinâmica de esturtura um pouco mais inteligênte
- Placeholder Selectors
- Etc

Com essa tech, facilmente conseguiremos manter uma produtividade melhor no desenvolvimento estrutural das páginas.

A documentação é curta demais e extremamente simples de compreender só ao olhar os exemplos.

O Sass é um dos Pré-processadores mais utilizados nas industrias tecnologicas.

_"Se tivéssemos conhecidos SASS antes, teríamos colocado muitas funcionalidades dela em CSS"_ - Hakon Wium Lie (Criador do CSS).

**Comment by raffacabofrio** [comment]
Muito bom campeão. Bem alinhado com a Sprint 4. A hora eh essa. Certamente os novos devs vão empolgar. Eh pra eles que a gente está focado agora.

Não vejo motivos pra não adotar. Pelo que vc falou só tem vantagens.

Único detalhe que eu acho que a gente deveria debater no slack antes de criar uma issue aqui.

Obrigado. 👊

**Comment by raffacabofrio** [comment]
Acho que a gente deveria fazer uma call para fazer o ONBOARDING dos novos membros. A gente agita isso lá no Slack e depois dessa call a gente vê o que faz aqui.

**Comment by raffacabofrio** [comment]
Por enquanto não vamos implantar o Sass no front.
