### ISSUE TITLE
Uso de ID na estrutura do projeto

### ISSUE THREAD

**Issue by thiagosantoscunha** [SharebookBR/sharebook-frontend#188]
O Angular nos permite um arquitetura baseada no escupo estrutural dos arquivos. Isso facilita bastante o uso de classes ao invés de ID. Dentro de alguns arquivos acabei percebendo o uso de IDs ao invés de classes. Já presenciei projetos dando problemas a medida que se extende, e ficava extremamente preocupante por não saber onde estava o erro.

A dica é aproveitar o uso do escopo estrutural para abusar de instâncias de classes, e não de #ids, e evitar problemas futuros.

**Comment by raffacabofrio** [comment]
Hmm... O pessoal de QA adora ids. Eles precisam muito para os testes integrados.

Inclusive uma das metas da Sprint 4 vai ser ter testes unitários e integrados rodando na hora que todos os deve estão com sangue nos olhos. Na hora que o Dev sabe tudo do código. Que hora eh essa?

Eh a hora do pull request. Então um dos aprovadores vai ser o APPVEYO, nosso serviço grátis de ci/cd. ( Para mais detalhes nessa parte procure a Val no canal #qa. )

**Comment by raffacabofrio** [comment]
Não vamos seguir em frente com essa issue. Motivo no comentário anterior.
