### ISSUE TITLE
Organização coesa da arquitetura estrutural do projeto

### ISSUE THREAD

**Issue by thiagosantoscunha** [SharebookBR/sharebook-frontend#189]
O projeto ainda está pequeno, mas a medida que estabelece um patamar grande no crescimento, ficará meio complexo a identificação dos componentes. Na verdade o que é UI, o que é Pagina, ou o que é uma funcionalidade básica.

Tudo isso, na grande maioria das vezes, o angular resume em _Components_. Mas, nada restrige o usuário de estabelecer uma organização coesa na estrutura organizacional.

Por exemplo:

1. Podemos facilmente disponibilizar um projeto a parte, chamado _**sharebook-ui**_, e disponibilizar este projeto no NPM para a comunidade usa-los em projetos pessoais. Com criação de um lybrary no angular podemos fazer isso. [Veja este link!](https://blog.angularindepth.com/creating-a-library-in-angular-6-87799552e7e5). Então, todo o componente referente a UI (Input, Radio, Button, Cards) estaria neste projeto.

2. Criação de um diretório _pages_ para manter os componentes que são páginas. Isso facilita bastante para o desenvolvedor identificar o problema.

3. Isolar os componentes de Pages em Modulos é importante para manter o projeto organizado, encapsulado e reaproveitável com funcionalidades extras que o modulo do angular pode oferecer. Como o Carregamento Tardio (LazyLoad)

4. Caso os componentes relacionados a UI venha ser encapsulados dentro de um Lib do angular, cada um dos componentes precisam estar dentro de um modulo. Ao usar o componente, ele precisa ser importado dentro do componente que será utlizado. Isso faz com que a performance vai lá em cima!

**Comment by raffacabofrio** [comment]
Muito bom. Será nossa prioridade agora.

**Comment by thiagosantoscunha** [comment]
Perfeito... estarei fechando essa Issue!

**Comment by raffacabofrio** [comment]
@thiagosantoscunha Legal. Então por favor pega a tarefa no trello, e coloca no seu nome e move pra DOING.

vlw
