### ISSUE TITLE
Usuário não consegue se cadastrar

### ISSUE THREAD

**Issue by raffacabofrio** [SharebookBR/sharebook-frontend#200]
Favor investigar.

**Comment by wantero** [comment]
Erro está acontecendo porque o valor informado no campo de Bairro está estourando o tamanho de varChar(30) do banco.

**Comment by raffacabofrio** [comment]
Ação corretiva:
- backend: aumentar limite desse campo para 50.
- frontend: limitar a quantidade durante a digitação.

Se possível, aproveitar que está com a mão na massa e ajustar demais campos.
- City, [Complement], [Country], [Neighborhood] de varChar(30) para varChar(50)
- [Street] de varChar(50) para varChar(80)

**Comment by raffacabofrio** [comment]
Ajustes de back ok.
