### ISSUE TITLE
Bug /livros/doar

### ISSUE THREAD

**Issue by mvromualdo** [SharebookBR/sharebook-frontend#202]
verificando as funcionalidades do WebSite, acabei me deparando com um "Bug" no FrontEnd, quando seleciono a opção de "não pagar pelo frete", abre um popup 

![image](https://user-images.githubusercontent.com/48070203/53568043-c1af9980-3b3f-11e9-944d-530376107410.png)

E quando clico no "clique aqui." fecha o popup sem acontecer nada, mas se eu apenas fixar o mouse me cima do "clique aqui." eu consigo ver que me redirecionaria para uma página do LinkedIn...

Até!

**Comment by raffacabofrio** [comment]
Missão cumprida. Obrigado @saraiva1989
