### ISSUE TITLE
[Fix] - Modulo node-sass não adicionado no package

### ISSUE THREAD

**Issue by lucasmiqueias** [SharebookBR/sharebook-frontend#209]
Galera acabei de baixar o projeto e tentei rodar, porém não tive exito porque estava faltando o Node-sass, e o sass-loader não funciona sem ele. Isso está certo?

**Comment by wantero** [comment]
git clone https://github.com/SharebookBR/sharebook-frontend.git
npm install
npm run start
projeto rodando normal

**Comment by lucasmiqueias** [comment]
Continua com erro após o start
```javascript
ERROR in ./src/style.scss
Module build failed: Error: `sass-loader` requires `node-sass` >=4. Please install a compatible version.
    at Object.sassLoader (/mnt/c/Projetos/sharebook-frontend/node_modules/sass-loader/lib/loader.js:31:19)
```

**Comment by wantero** [comment]
@lucasmiqueias Como isso não é uma issue a mesma foi encerrada. Que versão do Angular CLI você está? Poderia enviar as configurações do seu ambiente no canal #frontend no Slack? Vamos lhe auxiliar pelo canal do Slack.
