### ISSUE TITLE
Bug no frete.

### ISSUE THREAD

**Issue by raffacabofrio** [SharebookBR/sharebook-frontend#212]
Livro: https://sharebook.com.br/livros/incontadas
Frete: estado
Origem: SP

Minha origem: SP

Pra mim aparece "frete grátis: não". Enquanto deveria ser sim. E o checkbox não deveria aparecer.

**Comment by ralbertini** [comment]
<img width="886" alt="Captura de Tela 2019-04-01 às 12 43 25" src="https://user-images.githubusercontent.com/43758752/55340902-fafb6200-547b-11e9-9931-0febef3dce1f.png">

No cadastro deste livro, o frete está grátis. Quando estou logado, ele exibe certinho, mas quando não estou logado, ele exibe que o frete não é grátis.

**Comment by wantero** [comment]
Bug corrigido na PR #213
