### ISSUE TITLE
Texto sobre imagem nos detalhes do livro 

### ISSUE THREAD

**Issue by wantero** [SharebookBR/sharebook-frontend#215]
Acho que descobri o problema que tínhamos de às vezes o texto fica sobre a imagem nos detalhes do livro no Frontend Mobile.

Pelo que identifiquei isso acontece com o livro não está mais disponível. Analisei diversos livros e isso está acontecendo somente nesta situação.

**Comment by raffacabofrio** [comment]
Eu suspeito que tenha a ver com o tamanho do título.
