### ISSUE TITLE
[URGENTE] Erro ao buscar CEP

### ISSUE THREAD

**Issue by wantero** [SharebookBR/sharebook-frontend#219]
O Felipe reportou pelo Skype que quando informa o CEP o mesmo fica em looping e não trás os dados de endereço.

Avaliando, estamos com problema de CORS ao requisitar o WebService do viacep.com.br.

![image](https://user-images.githubusercontent.com/12854717/55628009-f7225500-5785-11e9-9bba-a75a948027ca.png)

**Comment by wantero** [comment]
Identifiquei o erro. 

Informei na tela o CEP 05717270 e o mesmo mandou para a URL como 05717-.

**Comment by wantero** [comment]
É algum pacote que está dando conflito com o ngx-mask. Fiz um clone do projeto e dei um npm install o erro foi replicado. Então copiei o diretório node_modules do meu repo para o repo do projeto e fiz o build local, subindo o mesmo via FTP para resolver o problema provisoriamente ate conseguir identificar o pacote que está dando conflito.

**Comment by renebentes** [comment]
Bom dia.

Tem essa lib https://github.com/filipedeschamps/cep-promise, pode ajudar nessa questão.

**Comment by wantero** [comment]
oi @renebentes. 

Esse componente ngx-mask que está com problemas utilizamos em outros campos para formatação.

Para a busca do CEP, hoje fazemos um get direto para https://viacep.com.br/ws/ e funciona legal :)

Mas bem interessante esse seu promisse. Que tal implementar ele no sharebook?

**Comment by renebentes** [comment]
Oi, @wantero.

Vou fazer um teste com ele, caso dê tudo certo envio PR.

**Comment by wantero** [comment]
Abri uma thread sobre o assunto no StackOverflow.

https://stackoverflow.com/questions/55653734/ngx-mask-error-after-upgrade-from-angular-6-to-7
