### ISSUE TITLE
SSL não é completamente seguro

### ISSUE THREAD

**Issue by mljunior** [SharebookBR/sharebook-frontend#227]
Algumas imagens precisam de revisão, pois não contém https no link, deixando assim o certificado SSL "quebrado".

![SSL- Quebrado](https://user-images.githubusercontent.com/42322809/56853697-a07de600-6901-11e9-933a-80740b339e0a.jpeg)
![Console](https://user-images.githubusercontent.com/42322809/56853698-a07de600-6901-11e9-955a-870763988187.jpeg)

**Comment by wantero** [comment]
@mljunior tudo bom?

Essas URL de imagens vem do endpoint. 

Vou encerrar a Issue aqui no Frontend. Você pode criar a mesma no repositório de Backend?

abs.
William Pavei Antero
