### ISSUE TITLE
SSL não é completamente seguro

### ISSUE THREAD

**Issue by mljunior** [SharebookBR/sharebook-frontend#228]
Algumas imagens precisam de revisão, pois não contém https no link, deixando assim o certificado SSL "quebrado".

![ssl](https://user-images.githubusercontent.com/42322809/56894459-4e9da300-6a5c-11e9-99e3-c8c2613c5013.jpeg)
![quebrado](https://user-images.githubusercontent.com/42322809/56894460-4e9da300-6a5c-11e9-87b9-95be5f4b1c73.jpeg)

**Comment by wantero** [comment]
@mljunior  tudo bom?

Essas URL de imagens vem do endpoint.

Vou encerrar a Issue aqui no Frontend. Você pode criar a mesma no repositório de Backend?
