### ISSUE TITLE
Erro quando se pesquisa por 'c#' em busca de livros

### ISSUE THREAD

**Issue by marcios** [SharebookBR/sharebook-frontend#234]
Quando se pesquisa por c# no campo de busca o site redireciona para a página de resultados porem neste momento ocorre um loop onde fica sendo apresentados msgs de alertas e aparentemente a página fica dando reload.

![erro_loop](https://user-images.githubusercontent.com/5693335/68772466-a2db2f80-0608-11ea-89ae-ac593d00ac8c.gif)

**Comment by maxgomes92** [comment]
Assina pra mim.

**Comment by wantero** [comment]
Correção já em produção.
