### ISSUE TITLE
Bug no menu da versão responsiva

### ISSUE THREAD

**Issue by lucalves** [SharebookBR/sharebook-frontend#235]
Olá!

Na versão responsiva, o menu de _Início_ está com um pequeno bug de alinhamento com relação aos outros itens do menu. 

Segue print com a demonstração:

![bug](https://i.imgur.com/k21Uj9g.png)

**Comment by raffacabofrio** [comment]
Obrigado por reportar @lucalves

**Comment by ErisvaldoCorreia** [comment]
Ação sendo corrigida com a PR #268

**Comment by lucalves** [comment]
Obrigado! @ErisvaldoCorreia 

Closing issue.
