### ISSUE TITLE
Máscara no cadastro

### ISSUE THREAD

**Issue by tomatealbertini** [SharebookBR/sharebook-frontend#92]
Na tela de cadastro, o formulário valida o formato do telefone e o CEP, mas o usuário que precisa formatar da forma correta, pois não tem máscara de telefone e CEP.

**Comment by raffacabofrio** [comment]
Tarefa no TRELLO:

https://trello.com/c/T6GmRmq1/12-mascaras-no-campo-telefone

**Comment by carlezzo** [comment]
Adicionado mascaras no campo de telefone e CEP PR #96
