### ISSUE TITLE
Orientação da foto na doação de livros

### ISSUE THREAD

**Issue by tomatealbertini** [SharebookBR/sharebook-frontend#93]
Testei no Opera, Chrome e Safari no iMac (todos com as versões mais atuais) e a foto do livro aparece rotacionada, ora para esquerda, ora de cabeça para baixo, dependendo do formato da foto (mais larga, mais estreita).

**Comment by raffacabofrio** [comment]
Tarefa no TRELLO:

https://trello.com/c/L53VK4Mz/16-bug-doar-livro-foto-do-livro-fica-girada-no-iphone

**Comment by thainan10** [comment]
@tomatealbertini tu poderias postar fotos aqui?
Fica mais fácil de rastrear o erro.
Acabei de testar no ambiente de teste e não tive nenhum problema:
![image](https://user-images.githubusercontent.com/7121678/45065872-e85dad80-b091-11e8-9c64-8ca052a350de.png)

Testado de um Macbook Air 13'' no Chrome.

**Comment by edvaldofarias** [comment]
Isso aconteceu comigo hoje ao fazer a doação de 5 livros, todos ficaram com a rotação para um dos lados.

**Comment by raffacabofrio** [comment]
Olá Edvaldo,

Putz esse bug eh chato e está no nosso radar.

Mas não se preocupe. Por enquanto eu mesmo vou corrigir as capas
manualmente.

Obrigado 👊

Em sáb, 8 de set de 2018 14:51, Edvaldo Farias <notifications@github.com>
escreveu:
